In [1]:
import sys
for i in sys.path:
    print(i)


C:\Anaconda\envs\qudi\python36.zip
C:\Program Files\Swabian Instruments\Time Tagger\driver\Python3.6\x64
C:\Anaconda\envs\qudi\DLLs
C:\Anaconda\envs\qudi\lib
C:\Anaconda\envs\qudi
C:\Anaconda\envs\qudi\lib\site-packages
C:\Anaconda\envs\qudi\lib\site-packages\IPython\extensions
C:\Users\Lukin SiV\.ipython


## The TimeTagger class

In [1]:
import TimeTagger as TT
import numpy as np

In [2]:
TT.setTimeTaggerChannelNumberScheme(TT.TT_CHANNEL_NUMBER_SCHEME_ONE)

In [3]:
TT.CHANNEL_UNUSED

-134217728

In [3]:
tagger = TT.createTimeTagger('1634000FX0')

In [5]:
tagger.reset()

In [6]:
tagger.getSerial()

'1634000FX0'

In [7]:
tagger.getModel()

'Time Tagger 20'

In [8]:
tagger.getTriggerLevel(1)

0.5

In [491]:
tagger.setTestSignal(1, False)

In [17]:
list(tagger.getChannelList(TT.TT_CHANNEL_RISING_AND_FALLING_EDGES))

[-8, -7, -6, -5, -4, -3, -2, -1, 1, 2, 3, 4, 5, 6, 7, 8]

In [18]:
tagger.getChannelList(tt.TT_CHANNEL_RISING_AND_FALLING_EDGES)

(-8, -7, -6, -5, -4, -3, -2, -1, 1, 2, 3, 4, 5, 6, 7, 8)

In [39]:
print(tagger.getChannelList(TT.TT_CHANNEL_RISING_AND_FALLING_EDGES))
print(tagger.getChannelList(TT.TT_CHANNEL_RISING_EDGES))
print(tagger.getChannelList(TT.TT_CHANNEL_FALLING_EDGES))

(-8, -7, -6, -5, -4, -3, -2, -1, 1, 2, 3, 4, 5, 6, 7, 8)
(1, 2, 3, 4, 5, 6, 7, 8)
(-1, -2, -3, -4, -5, -6, -7, -8)


In [364]:
tagger.setTestSignal(1, True)

## Virtual Channels

### Combiner

In [9]:
combined_channel = TT.Combiner(tagger=tagger, channels=[1, 2])

In [10]:
combined_channel

<TimeTagger.Combiner; proxy of <Swig Object of type 'Combiner *' at 0x000001D9EC051F90> >

In [11]:
combined_channel.getChannel()

9

##### Test with Counter measurement

In [12]:
test_counter = TT.Counter(tagger=tagger, channels=[combined_channel.getChannel()])

In [17]:
tagger.setTestSignal(1, True)

In [18]:
tagger.setTestSignal(1, False)

In [19]:
tagger.setTestSignal(2, True)

In [20]:
tagger.setTestSignal(2, False)

In [21]:
len(['a'])

1

In [22]:
len(1)

TypeError: object of type 'int' has no len()

## Measurement Classes

### Counter

In [12]:
cntr1 = tt.Counter(tagger=tagger, channels=[1, 2], binwidth=int(1e12), n_values=10)

In [6]:
tagger.setTestSignal(1, True)

In [13]:
cntr1.start()

In [480]:
cntr1.clear()

In [56]:
cntr1.stop()

NameError: name 'cntr1' is not defined

In [14]:
print(cntr1.getCaptureDuration())
print(cntr1.getData())
# cntr.clear()

5470486026000
[[     0      0      0      0      0 801764 801736 801810 801726 801680]
 [     0      0      0      0      0      0      0      0      0      0]]


In [11]:
cntr1.getCaptureDuration()

31123808400000

In [16]:
data_ar = cntr1.getData()

In [31]:
data_ar

array([[801603, 801593, 801626, 801687, 801608, 801656, 801757, 801747,
        801758, 801685],
       [     0,      0,      0,      0,      0,      0,      0,      0,
             0,      0]], dtype=int32)

In [46]:
data_ar[0:2, -2:]

array([[801758, 801685],
       [     0,      0]], dtype=int32)

In [43]:
count_ar = [data_ar[]]

array([[801603, 801593, 801626, 801687, 801608, 801656, 801757, 801747,
        801758, 801685],
       [     0,      0,      0,      0,      0,      0,      0,      0,
             0,      0]], dtype=int32)

In [21]:
data_ar[0, 1]

801593

In [24]:
test_ar = np.zeros(shape=(2, 10), dtype=np.uint32)

In [28]:
test_ar[:][:] = [data_ar[i, j] for i in range(2) j in range(10)]

SyntaxError: invalid syntax (<ipython-input-28-ad9a905c030b>, line 1)

In [ ]:
test_ar

In [11]:
cntr2 = TT.Counter(tagger=tagger, channels=[1], binwidth=int(1e6), n_values=10)

In [4]:
cntr2.start()

NameError: name 'cntr2' is not defined

In [31]:
tagger.setTestSignal(2, True)

In [70]:
cntr2.getData()

array([[0, 1, 1, 1, 1, 0, 1, 1, 1, 1]], dtype=int32)

In [79]:
cntr2.getCaptureDuration()

21396344208000

### CountBetweenMarkers

In [6]:
gated_cntr = TT.CountBetweenMarkers(
    tagger=tagger,
    click_channel=1, 
    begin_channel=2, 
    end_channel=-2, 
    n_values=20
)

In [7]:
gated_cntr.getData()

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int32)

In [66]:
gated_cntr.getCaptureDuration()

27273068544000

In [40]:
gated_cntr.clear()

In [46]:
gated_cntr.isRunning()

False

In [44]:
gated_cntr.ready()

False

In [45]:
gated_cntr.stop()

In [47]:
gated_cntr.start()

In [53]:
gated_cntr.isRunning()

True

##### Run test

In [62]:
print(gated_cntr.getData())
print('isRunnig(): {}'.format(gated_cntr.isRunning()))
print('ready(): {}'.format(gated_cntr.ready()))

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
isRunnig(): True
ready(): False


In [100]:
gated_cntr.clear()